### ISSUE TITLE
Trying to deploy as a headless server on a server without display capabilities does not work.

### ISSUE THREAD

**Issue by aleksfadini** [Jibby-Games/Flappy-Race#126]
When I try to run the linux binary as a headless server in linux, I get this error

```
 ./FlappyRace.x86_64 --headless --server
Godot Engine v3.5.2.stable.official.170ba337a - https://godotengine.org
ERROR: X11 Display is not available
   at: initialize (platform/x11/os_x11.cpp:143)
```

**Comment by aleksfadini** [comment]
Thank you for advising, the suggested solution is to run godot in a dockerfile.
Using the following command:

`ENTRYPOINT [ "/usr/local/bin/godot-server", "--main-pack", "server.pck" ]`

I can look into adding headless binaries to the releases as well at some point
You can grab the server version of Godot here https://godotengine.org/download/3.x/server/

**Comment by Jibbajabbafic** [comment]
Provided the above solution over discord to Aleks
