### ISSUE TITLE
Make a proper server node/project

### ISSUE THREAD

**Issue by wildjames** [Jibby-Games/Flappy-Race#17]
I'm thinking that we take out self-hosting and make a dedicated server project. It just seems the most Godot-y way to do this if we want to separate the server and client codes. We could have:

Client sends:
  - Flap events as they occur
  - Position updates (unreliable) per frame
  - Score events as they occur
  - Death events as they occur
 
Server sends:
  - Wall parameters as they spawn in
  - Difficulty increase events as they occur
  - [EDIT] Fellow player locations

Server also sanity-checks player locations at the end of a game as an anti-cheat mechanism.

Any better ideas?

**Comment by Jibbajabbafic** [comment]
I think it would be a real shame to lose self-hosting since it makes setting up a game so much easier and more intuitive. I've been tinkering around in a project and you can get a separate client and server node within the same project to connect to each other so I don't see that as an issue.

Another advantage of that way is the server and client can share the same scenes (players and walls etc) which we'll need for server side collision detection anyways, so it makes the project much easier to maintain

**Comment by wildjames** [comment]
We don't necessarily lose the self-hosting functionality - [Godot can run external binaries](https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-execute) just fine. Wouldn't be too difficult to have the `Host` button start the server, then connect the "host" player as just another client over localhost, while the others come in over the internet.


> the server and client can share the same scenes (players and walls etc)

This is a good point. Although, I don't think server-side collision detection is going to be very robust mostly due to lag. Some testing on my side with purely p2p multiplayer, in which connected clients have a mirrored server-side sprite with its own collision detection, has relatively frequent erroneous server-side collision detections. It becomes way more common as the speed increases, and gets almost unavoidable at a score of about 30 or so. I think it'd be too frustrating doing remote detections on a game as fast as this.

**Comment by wildjames** [comment]
That said, I didn't look at the master/slave version, which may be better

**Comment by Jibbajabbafic** [comment]
We'd need to add proper client side prediction and lag compensation if we want it to handle collisions on the server, which is covered in those video tutorials I send the other day. Shouldn't be too bad to implement

**Comment by Jibbajabbafic** [comment]
Hmm I think it will be a lot simpler to just separate the client and server after tinkering with the combined version. I'll test it out with them separated
