### ISSUE TITLE
Show a leaderboard in multiplayer

### ISSUE THREAD

**Issue by Easty12345** [Jibby-Games/Flappy-Race#24]
Show a leaderboard with all players on it, and their current score along the side or in the corner.
This can also show the status of each player and can show a small icon such as a skull to show which players are dead.

Here's a basic mockup of what it could look like (feel free to change it if you have other ideas):
![image](https://user-images.githubusercontent.com/4493127/119967912-c3799900-bfa4-11eb-808d-e36b458340b7.png)

**Comment by Jibbajabbafic** [comment]
Added in #44
