### ISSUE TITLE
Android version?

### ISSUE THREAD

**Issue by wildjames** [Jibby-Games/Flappy-Race#9]
Godot seems to support building APK. I wonder if our code is portable to android by default? Would need looking into, but low priority.

**Comment by Jibbajabbafic** [comment]
Protip you can use the labels to mark issues. I made a couple for low priority and high priority issues
![image](https://user-images.githubusercontent.com/4493127/114301851-5fffde80-9abe-11eb-94bd-ea0ff170ac33.png)

**Comment by wildjames** [comment]
Nice, thanks
